services:
  nginx:
    image: nginx:latest
    container_name: gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    networks:
      - breezy-net

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - breezy-net

  backend:
    build: ./backend
    container_name: backend
    networks:
      - breezy-net

  auth:
    build: ./auth
    container_name: auth
    networks:
      - breezy-net

networks:
  breezy-net:
    driver: bridge
