version: '3.8'

services:
  mongo:
    image: mongo
    container_name: breezy-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - breezy-net

  auth:
    build: ./backend/auth
    container_name: breezy-auth
    expose:
      - "4000"
    env_file:
      - ./backend/auth/.env
    depends_on:
      - mongo
    networks:
      - breezy-net

  users:
    build: ./backend/users
    container_name: breezy-users
    expose:
      - "5000"
    env_file:
      - ./backend/users/.env
    depends_on:
      - mongo
      - auth
    networks:
      - breezy-net

  post:
    build: ./backend/posts
    container_name: breezy-post
    expose:
      - "5000"
    env_file:
      - ./backend/posts/.env
    depends_on:
      - mongo
      - auth
    networks:
      - breezy-net

  frontend:
    build: ./frontend
    container_name: breezy-frontend
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - users
      - post
    networks:
      - breezy-net

  nginx:
    image: nginx:latest
    container_name: breezy-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./backend/gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth
      - users
      - post
      - frontend
    networks:
      - breezy-net

networks:
  breezy-net:
    driver: bridge

volumes:
  mongo_data:
