services:
  mongo:
    image: mongo
    restart : always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  auth:
    build: ./backend/auth
    expose:
      - "5000"
    env_file:
      - ./backend/auth/.env
    networks:
      - app-network

  tasks:
    build: ./backend/tasks
    expose:
      - "5000"
    env_file:
      - ./backend/tasks/.env
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - nginx
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: gateway
    volumes:
      - ./backend/gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - auth
      - tasks
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo_data: