services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - breezy-net

  users:
    build: ./backend/users
    expose:
      - "5000"
    env_file:
      - ./backend/users/.env
    networks:
      - breezy-net

  auth:
    build: ./backend/auth
    container_name: auth
    expose:
      - "4000"
    env_file:
      - ./backend/.env
    networks:
      - breezy-net

  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "3000"
    depends_on:
      - auth
      - users
    networks:
      - breezy-net

  nginx:
    image: nginx:latest
    container_name: gateway
    ports:
      - "8080:8080"
    volumes:
      - ./backend/gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth
      - users
      - frontend
    networks:
      - breezy-net

networks:
  breezy-net:
    driver: bridge

volumes:
  mongo_data:
