version: '3.8'

services:
  # Base de données MongoDB
  mongo:
    image: mongo
    container_name: breezy-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - breezy-net

  # Service d'authentification (login/register/refresh)
  auth:
    build: ./backend/auth
    container_name: breezy-auth
    expose:
      - "4000"
    env_file:
      - ./backend/auth/.env
    depends_on:
      - mongo
    networks:
      - breezy-net

  # Service de gestion des utilisateurs (profils publics, follow)
  users:
    build: ./backend/users
    container_name: breezy-users
    expose:
      - "5000"
    env_file:
      - ./backend/users/.env
    depends_on:
      - mongo
      - auth
    networks:
      - breezy-net

  # Service des publications (posts, commentaires, likes)
  post:
    build: ./backend/posts
    container_name: breezy-post
    expose:
      - "5000" # 🟡 attention : même port que users, ce qui n’a pas d’impact ici car ce sont des ports internes
    env_file:
      - ./backend/posts/.env
    depends_on:
      - mongo
      - auth
    networks:
      - breezy-net

  # Interface utilisateur (frontend React / Next.js)
  frontend:
    build: ./frontend
    container_name: breezy-frontend
    ports:
      - "3000:3000" # accessible depuis l’hôte
    depends_on:
      - auth
      - users
      - post
    networks:
      - breezy-net

  # Gateway NGINX (reverse proxy unifié vers auth, users, posts, frontend)
  nginx:
    image: nginx:latest
    container_name: breezy-gateway
    ports:
      - "8080:8080" # exposé à l’extérieur
    volumes:
      - ./backend/gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth
      - users
      - post
      - frontend
    networks:
      - breezy-net

# Réseau privé pour tous les services
networks:
  breezy-net:
    driver: bridge

# Volume persistant pour MongoDB
volumes:
  mongo_data:
