version: "3.9"

services:
  auth:
    build: ./backend/auth
    ports:
      - "5001:5000"
    env_file:
      - ./backend/auth/.env

  feed:
    build: ./backend/feed
    ports:
      - "5002:5000"
    env_file:
      - ./backend/feed/.env

  tasks:
    build: ./backend/tasks
    ports:
      - "5003:5000"
    env_file:
      - ./backend/tasks/.env

  gateway:
    build: ./backend/gateway
    ports:
      - "8000:8000"
    env_file:
      - ./backend/gateway/.env
    depends_on:
      - auth
      - feed
      - tasks

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - gateway
