services:
  mongo:
    image: mongo
    restart : always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - breezy-net

  tasks:
    build: ./backend/tasks
    expose:
      - "5000"
    env_file:
      - ./backend/tasks/.env
    networks:
      - breezy-net

  nginx:
    image: nginx:latest
    container_name: gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - tasks
    networks:
      - breezy-net

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - nginx
    networks:
      - breezy-net

  backend:
    build: ./backend
    container_name: backend
    networks:
      - breezy-net

  auth:
    build: ./auth
    container_name: auth
    networks:
      - breezy-net

networks:
  breezy-net:
    driver: bridge

volumes:
  mongo_data:
